// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBB3YB542tXXrfGIwUvFv7GFGvdJ7RA4OE',
    appId: '1:491944466356:web:9a2247382bc3b9c7c484e1',
    messagingSenderId: '491944466356',
    projectId: 'child-tracker-91bcd',
    authDomain: 'child-tracker-91bcd.firebaseapp.com',
    storageBucket: 'child-tracker-91bcd.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDSPc4kHe64jgWtyo-uNBSEi8V1imNLjSk',
    appId: '1:491944466356:android:30c1b905d780f03fc484e1',
    messagingSenderId: '491944466356',
    projectId: 'child-tracker-91bcd',
    storageBucket: 'child-tracker-91bcd.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAPMEsX073TqUnLGYQwd1CSHzoODQCkUyU',
    appId: '1:491944466356:ios:a5528d7871a171c9c484e1',
    messagingSenderId: '491944466356',
    projectId: 'child-tracker-91bcd',
    storageBucket: 'child-tracker-91bcd.firebasestorage.app',
    iosBundleId: 'com.example.childTracker',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAPMEsX073TqUnLGYQwd1CSHzoODQCkUyU',
    appId: '1:491944466356:ios:a5528d7871a171c9c484e1',
    messagingSenderId: '491944466356',
    projectId: 'child-tracker-91bcd',
    storageBucket: 'child-tracker-91bcd.firebasestorage.app',
    iosBundleId: 'com.example.childTracker',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBB3YB542tXXrfGIwUvFv7GFGvdJ7RA4OE',
    appId: '1:491944466356:web:fa8b86fd61854c73c484e1',
    messagingSenderId: '491944466356',
    projectId: 'child-tracker-91bcd',
    authDomain: 'child-tracker-91bcd.firebaseapp.com',
    storageBucket: 'child-tracker-91bcd.firebasestorage.app',
  );
}
